name: Build Docker image and push to ACR registry

on:
  #push:
   # branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]
    workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code 
      uses: actions/checkout@v3
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account show
            az storage -h
            
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${ secrets.REGISTRY_NAME }.azurecr.io
        username: ${ secrets.ACR_USERNAME }
        password: ${ secrets.ACR_PASSWORD }
        
    - run: |
       az acr login --name PoojaDevOpsContainerRegistry
       docker build . -t poojadevopscontainerregistry.azurecr.io/poojadevopsspringbootimage:${{ github.sha }}
       docker push poojadevopscontainerregistry.azurecr.io/poojadevopsspringbootimage:${{ github.sha }}
        
      
  
      
